name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: 拉取存储库
        run: |
          git clone https://gitlab.com/proot/proot.git work
          cd work && git checkout origin/release/v5.3.1 && cd ..

      - name: 启动 docker
        run: docker run -i -d --name=gcc --tmpfs /tmp -v 'work:/w' gcc:7.4.0 bash

      - name: 安装依赖
        run: |
          docker exec gcc bash -c 'apt update -qq'
          docker exec gcc bash -c 'apt-get install -qq clang-tools-6.0 curl docutils-common gdb lcov libarchive-dev libtalloc-dev strace swig uthash-dev xsltproc'

      - name: 构建
        run: |
          docker exec gcc bash -c "ls /w"
          docker exec gcc bash -c 'LDFLAGS="${LDFLAGS} -static" make -C /w/src proot'
          mkdir -p dist
          cp work/src/proot dist/
          cd dist
          sha256sum ./proot > proot.sha256sum
          md5sum ./proot > proot.md5sum

      - name: 下载产物
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: ./dist/*
